global.projectConstant = {
  apiURL: "http://192.168.0.160:8080",
  colors: ["#c2f9bb", "9ad1d4", "62c370", "cc3363", "20063b"],
  poiOptions: [
    { key: "Temple", value: "Temple", text: "Temple" },
    { key: "beach", value: "beach", text: "Beach" },
    { key: "restaurant", value: "restaurant", text: "Restaurant" },
    { key: "FireStation", value: "FireStation", text: "Fire Station" },
    { key: "Police office", value: "Police office", text: "Police Office" },
    { key: "coffee", value: "coffee", text: "Coffee" },
    { key: "post office", value: "post office", text: "Post Office" },
    { key: "bank", value: "bank", text: "Bank" },
    { key: "hospital", value: "hospital", text: "Hospital" },
    { key: "McDonald", value: "McDonald", text: "McDonald" },
    { key: "Mall", value: "Mall", text: "Mall" },
    { key: "sport center", value: "sport center", text: "Sport Center" },
    { key: "supermarket", value: "supermarket", text: "Supermarket" },
    { key: "store", value: "store", text: "Store" },
    { key: "school", value: "school", text: "School" },
    { key: "parking lot", value: "parking lot", text: "Parking Lot" },
    { key: "Gas station", value: "Gas station", text: "Gas Station" },
    { key: "garden", value: "garden", text: "Garden" },
    { key: "park", value: "park", text: "Park" },
    { key: "bar", value: "bar", text: "Bbar" },
    { key: "ATM", value: "ATM", text: "ATM" },
    { key: "Theater", value: "Theater", text: "Theater" },
    { key: "University", value: "University", text: "University" },
    { key: "bus terminal", value: "bus terminal", text: "Bus Terminal" }
  ],
  regionName: [
    { key: "Aberdeen", value: "Aberdeen", text: "Aberdeen" },
    { key: "Ap Lei Chau", value: "Ap Lei Chau", text: "Ap Lei Chau" },
    { key: "Baguio Villa", value: "Baguio Villa", text: "Baguio Villa" },
    { key: "Causeway Bay", value: "Causeway Bay", text: "Causeway Bay" },
    { key: "Chai Wan", value: "Chai Wan", text: "Chai Wan" },
    { key: "Cheung Chau", value: "Cheung Chau", text: "Cheung Chau" },
    { key: "Cheung Sha Wan", value: "Cheung Sha Wan", text: "Cheung Sha Wan" },
    {
      key: "Clear Water Bay",
      value: "Clear Water Bay",
      text: "Clear Water Bay"
    },
    { key: "Diamond Hill", value: "Diamond Hill", text: "Diamond Hill" },
    { key: "Discovery Bay", value: "Discovery Bay", text: "Discovery Bay" },
    { key: "Fan Ling", value: "Fan Ling", text: "Fan Ling" },
    {
      key: "Fortress Hill Road",
      value: "Fortress Hill Road",
      text: "Fortress Hill Road"
    },
    { key: "Fotan", value: "Fotan", text: "Fotan" },
    { key: "Happy Valley", value: "Happy Valley", text: "Happy Valley" },
    { key: "Heng Fa Chuen", value: "Heng Fa Chuen", text: "Heng Fa Chuen" },
    { key: "Ho Man Tin", value: "Ho Man Tin", text: "Ho Man Tin" },
    { key: "Hung Hom", value: "Hung Hom", text: "Hung Hom" },
    { key: "Japan", value: "Japan", text: "Japan" },
    { key: "Jardine", value: "Jardine", text: "Jardine" },
    { key: "Jordan", value: "Jordan", text: "Jordan" },
    { key: "Kennedy Town", value: "Kennedy Town", text: "Kennedy Town" },
    { key: "Kowloon Bay", value: "Kowloon Bay", text: "Kowloon Bay" },
    { key: "Kowloon City", value: "Kowloon City", text: "Kowloon City" },
    {
      key: "Kowloon Station",
      value: "Kowloon Station",
      text: "Kowloon Station"
    },
    { key: "Kowloon Tong", value: "Kowloon Tong", text: "Kowloon Tong" },
    { key: "Kwai Chung", value: "Kwai Chung", text: "Kwai Chung" },
    { key: "Kwai Fong", value: "Kwai Fong", text: "Kwai Fong" },
    { key: "Kwun Tong", value: "Kwun Tong", text: "Kwun Tong" },
    { key: "Lai Chi Kok", value: "Lai Chi Kok", text: "Lai Chi Kok" },
    { key: "Lai King", value: "Lai King", text: "Lai King" },
    { key: "Lam Tin", value: "Lam Tin", text: "Lam Tin" },
    { key: "Lok Fu", value: "Lok Fu", text: "Lok Fu" },
    { key: "Ma On Shan", value: "Ma On Shan", text: "Ma On Shan" },
    { key: "Ma Wan", value: "Ma Wan", text: "Ma Wan" },
    { key: "Mei Foo", value: "Mei Foo", text: "Mei Foo" },
    { key: "Mid-Levels", value: "Mid-Levels", text: "Mid-Levels" },
    { key: "Mong Kok", value: "Mong Kok", text: "Mong Kok" },
    { key: "Ngau Chi Wan", value: "Ngau Chi Wan", text: "Ngau Chi Wan" },
    { key: "Ngau Tau Kok", value: "Ngau Tau Kok", text: "Ngau Tau Kok" },
    { key: "North Point", value: "North Point", text: "North Point" },
    {
      key: "North Point Mid",
      value: "North Point Mid",
      text: "North Point Mid"
    },
    { key: "Olympic", value: "Olympic", text: "Olympic" },
    { key: "Pok Fu Lam", value: "Pok Fu Lam", text: "Pok Fu Lam" },
    { key: "Prince Edward", value: "Prince Edward", text: "Prince Edward" },
    { key: "Quarry Bay", value: "Quarry Bay", text: "Quarry Bay" },
    { key: "Repulse Bay", value: "Repulse Bay", text: "Repulse Bay" },
    { key: "Sai Kung", value: "Sai Kung", text: "Sai Kung" },
    { key: "Sai Wan Ho", value: "Sai Wan Ho", text: "Sai Wan Ho" },
    { key: "Sai Yin Pun", value: "Sai Yin Pun", text: "Sai Yin Pun" },
    { key: "San Po Kong", value: "San Po Kong", text: "San Po Kong" },
    { key: "Sham Shui Po", value: "Sham Shui Po", text: "Sham Shui Po" },
    { key: "ShaTin", value: "ShaTin", text: "ShaTin" },
    { key: "Shaukeiwan", value: "Shaukeiwan", text: "Shaukeiwan" },
    { key: "Shek Tong Tsui", value: "Shek Tong Tsui", text: "Shek Tong Tsui" },
    { key: "Sheung Shui", value: "Sheung Shui", text: "Sheung Shui" },
    { key: "Sheung Wan", value: "Sheung Wan", text: "Sheung Wan" },
    { key: "South Horizons", value: "South Horizons", text: "South Horizons" },
    {
      key: "South Lantau Island",
      value: "South Lantau Island",
      text: "South Lantau Island"
    },
    {
      key: "Southern District",
      value: "Southern District",
      text: "Southern District"
    },
    { key: "Tai Hang", value: "Tai Hang", text: "Tai Hang" },
    { key: "Tai Kok Tsui", value: "Tai Kok Tsui", text: "Tai Kok Tsui" },
    { key: "Tai Po", value: "Tai Po", text: "Tai Po" },
    { key: "Tai Wai", value: "Tai Wai", text: "Tai Wai" },
    { key: "Taikoo Shing", value: "Taikoo Shing", text: "Taikoo Shing" },
    { key: "Tin Hau", value: "Tin Hau", text: "Tin Hau" },
    { key: "Tin Shui Wai", value: "Tin Shui Wai", text: "Tin Shui Wai" },
    { key: "To Kwa Wan", value: "To Kwa Wan", text: "To Kwa Wan" },
    { key: "Tseung Kwan O", value: "Tseung Kwan O", text: "Tseung Kwan O" },
    { key: "Tsim Sha Tsui", value: "Tsim Sha Tsui", text: "Tsim Sha Tsui" },
    { key: "Tsing Yi", value: "Tsing Yi", text: "Tsing Yi" },
    { key: "Tsuen Wan", value: "Tsuen Wan", text: "Tsuen Wan" },
    {
      key: "Tsuen Wan Sham Tseng",
      value: "Tsuen Wan Sham Tseng",
      text: "Tsuen Wan Sham Tseng"
    },
    { key: "Tuen Mun", value: "Tuen Mun", text: "Tuen Mun" },
    {
      key: "Tuen Mun Sham Tseng",
      value: "Tuen Mun Sham Tseng",
      text: "Tuen Mun Sham Tseng"
    },
    { key: "Tung Chung", value: "Tung Chung", text: "Tung Chung" },
    { key: "Wan Chai", value: "Wan Chai", text: "Wan Chai" },
    {
      key: "Western mid-levels",
      value: "Western mid-levels",
      text: "Western mid-levels"
    },
    { key: "Whampo", value: "Whampo", text: "Whampo" },
    { key: "Wong Chuk Hang", value: "Wong Chuk Hang", text: "Wong Chuk Hang" },
    { key: "Wong Tai Sin", value: "Wong Tai Sin", text: "Wong Tai Sin" },
    { key: "Yau Ma Tei", value: "Yau Ma Tei", text: "Yau Ma Tei" },
    { key: "Yau Tong", value: "Yau Tong", text: "Yau Tong" },
    { key: "Yau Yat Tsuen", value: "Yau Yat Tsuen", text: "Yau Yat Tsuen" },
    { key: "Yuen Long", value: "Yuen Long", text: "Yuen Long" }
  ]
};
